# absolute or relative path
source_dir: ../source_dir/

# absolute or relative path
output_dir: ../output_dir/

# automatic rename your when you initialize a book:
# - volume-folders (if there are 2 folder-levels) to volume_{number_zerofill}
# - chapter-folders to chapter_{number_zerofill}
# - images which are in your chapter-folders to img_{number_zerofill}0.{extension}
# files are sorted alphanumeric
# after rename each name will only exist once in the entire source-folder
# files and folders starting with "__" (2 underscores) are ignored in general
# images outside the chapter-folders ar also ignored for rename
# if it got stuck, coz you have opened a file/folder and block access - dont-worry - start it twice
rename: yes


# resize-method for images which don't have the book-size
default_resize_method: cropmax

# max 1800
default_resize_width: 900

# max 2400
default_resize_height: 1200

# highest compression is 0, 100 for lossless
default_webp_compression: 75

# compress all images with webp
default_compress_all: yes

# manga or comic
default_book_type: manga


# ISO 639-1 language-code
default_book_language: en