# absolute or relative path
source_dir: ../source_dir/

# absolute or relative path
output_dir: ../output_dir/


# resize-method for images that don't have the resize-size. It will store them as webp to the *.ecmb when you build it
# !!!! Your source files stay untouched !!!!
# available methods:
# - none: does nothing to your files
# - max: resizes the images with their aspect ratio to fit in the resize box
#     - good for minimizing the file size of your *.ecmb
# - stretch: stretches the images to the resize-size, the images will lose their original aspect ratio
# - cover: will resize the images to the box with their original aspect ratio and cut off the overhanging parts
# - cropmax: crops the white borders on the x-axis and then resizes the images with their aspect ratio to fit in the resize box.
#    - good for downloaded images, which often have wired borders. A single gray dot (from the scanning process) can disturb doing this, so it won't work 100%
default_resize_method: max

# max 1800
default_resize_width: 900

# max 2400
default_resize_height: 1200

# highest compression is 0, 100 for lossless
default_webp_compression: 75

# compress all images with webp, even if they are not resized
# !!!! Your source files stay untouched !!!!
# good for minimizing the file size of your *.ecmb
# avaliable values
# - true
# - false
default_compress_all: true

# available values: 
# - manga
# - comic
default_book_type: manga


# ISO 639-1 language-code (https://localizely.com/iso-639-1-list/)
default_book_language: en