# absolute or relative path
source_dir: ../source_dir/

# absolute or relative path
output_dir: ../output_dir/


# resize-method for images which don't have the resize-size and stores it as webp to the *.ecmb when you build it
# !!!! your source-files stay untouched !!!!
# available methods:
# - none: does nothing to your files
# - max: resizes the images with it's aspect-ratio to fit in the resize box
# -      - good for minimize the file-size of your *.ecmb
# - stretch: strechtes the image to the resize-size, the image will lose its original aspect-ratio
# - cover: will resize the image to the box with its original aspect-ratio and cut off the overhanging parts
# - cropmax: crops the white borders on the x-axis and then resizes the images with it's aspect-ratio to fit in the resize box.
#            - good for downloaded images which often have wired borders. A single grey dot (from the scanning-process) can disturb doing this.
default_resize_method: max

# max 1800
default_resize_width: 900

# max 2400
default_resize_height: 1200

# highest compression is 0, 100 for lossless
default_webp_compression: 75

# compress all images with webp, even if they are not resized stores to the *.ecmb when you build it
# !!!! your source-files stay untouched !!!!
# good for minimize the file-size of your *.ecmb
# avaliable values
# - true
# - false
default_compress_all: true

# available types: 
# - manga
# - comic
default_book_type: manga


# ISO 639-1 language-code
default_book_language: en